# Generated by Django 2.0.6 on 2018-06-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='save',
            new_name='complete',
        ),
    ]
